package emailAdmin;

import java.util.Scanner;

public class EmailAdmin {

	private String firstName, lastName, department, company = "ABC";
	private String password, passwordStatus = "not okay";
	private String mainEmailAddress, alternateEmailAddress;
	private int mailboxCapacity, choice, passwordLength = 0;
	boolean altEmail = false;
	private boolean isUserPassword = false;
	private static Scanner sc = new Scanner(System.in);

	// take input and ask for department
	void takeInput() {

		System.out.print("\nEnter your first name : ");
		firstName = sc.nextLine();
		firstName = firstName.replaceAll(" ", "");

		System.out.print("\nEnter your last name : ");
		lastName = sc.nextLine();
		lastName = lastName.replaceAll(" ", "");

		department = getDepartment();

		System.out.println("\nEmail Address is being generated...");
		mainEmailAddress = generateEmailAddress();
		System.out.println("\n----------EMAIL ID generated----------");
		sc.nextLine();

		System.out.print("\nDo you want to set password yourself? : Yes or No : ");
		String passChoice = sc.nextLine();
		passChoice = passChoice.toLowerCase();

		if (passChoice.equals("yes") || passChoice.equals("y")) {

			while (passwordStatus.equals("not okay")) {

				System.out.println("\nEnter a password of your choice : ");
				String userPassword = sc.nextLine();
				isUserPassword = true;

				if (PasswordChecks.isPasswordValid(userPassword, isUserPassword)) {
					passwordStatus = "ok";
					setPassword(userPassword); // password setting
					System.out.println("\n----------Password has been accepted by the system.----------");
				} else {
					System.out.println("\nSome parameters are not met. Try another password.");
				}
			}
		} else {
			password = generatePassword();
			sc.nextLine();
		}

		System.out.println("\nSetting up the inital mailbox capacity...");
		setMailBoxCapacity(500);
		System.out.println("\n----------Mailbox capacity has been set to default----------");

		System.out.print("\nDo you want an alternate email address? Yes or No : ");
		String altEmailChoice = sc.nextLine();
		altEmailChoice = altEmailChoice.toLowerCase();

		if (altEmailChoice.equals("yes") || altEmailChoice.equals("y")) {
			altEmail = true;
			setAlternateEmailAddress();
		}

	}

	// get the department
	private String getDepartment() {
		department = setDepartment();
		return department;
	}

	// setting the department
	private String setDepartment() {

		System.out.print(
				"\nEnter the department : \n1. Sales\n2. Development\n3. Accounting\n0. None\nEnter the department choice : ");
		choice = sc.nextInt();

		switch (choice) {
		case (0): {
			department = "";
			break;
		}
		case (1): {
			department = "sales";
			break;
		}
		case (2): {
			department = "dev";
			break;
		}
		case (3): {
			department = "accounts";
			break;
		}
		}
		return department;
	}

	// generate email address
	private String generateEmailAddress() {
		return firstName.toLowerCase() + "." + lastName.toLowerCase() + "@" + department.toLowerCase() + "."
				+ company.toLowerCase() + ".com";
	}

	// generate a password
	private String generatePassword() {
		while (passwordLength < 8) {
			System.out.print(
					"\nYour password will be generated by the system...\n\nPlease enter your desired length for the password : ");
			passwordLength = sc.nextInt();
			System.out.println("\nGenerating password...");
			if (passwordLength < 8) {
				System.out.println("\nPassword length must be greater than 7");
			}
		}
		String charToChooseFrom = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()";
		int optionLength = charToChooseFrom.length();
		String passwordStr = "";

		while (passwordStatus.equals("not okay")) {
			for (int i = 0; i < passwordLength; i++) {
				passwordStr += charToChooseFrom.charAt((int) (Math.random() * optionLength));
			}
			if (PasswordChecks.isPasswordValid(passwordStr, isUserPassword)) {
				passwordStatus = "okay";
			} else {
				passwordStr = "";
			}
		}
		System.out.println("\n----------Password has been generated----------");
		return passwordStr;

	}

	protected void setPassword(String password) {
		this.password = password;
	}

	protected void setMailBoxCapacity(int mailboxCapacity) {
		this.mailboxCapacity = mailboxCapacity;
	}

	// protected so that visible in other class
	protected String getAlternateEmailAddress() {
		return alternateEmailAddress;
	}

	// protected so that visible in other class
	protected String getName() {
		return firstName + " " + lastName;
	}

	// protected so that visible in other class
	protected String getEmail() {
		return mainEmailAddress;
	}

	// protected so that visible in other class
	protected int getMailboxCapacity() {
		return mailboxCapacity;
	}

	// protected so that visible in other class
	protected String getPassword() {
		return password;
	}

	protected void setAlternateEmailAddress() {
		System.out.println("\n\nWe support 5 email domains. Gmail, Yahoo, Hotmail, Outlook, Redditmail.");
		// System.out.println("In the next steps, the system will ask to select email
		// domain.");
		System.out.println(
				"Please make sure that your email address is valid as cross checking is not possible at the moment.");
		int confirmChoice = 0;

		while (confirmChoice != 1 || confirmChoice != 3) {
			System.out.println("\n\nPlease choose your domain : ");
			System.out.println("1.@gmail.com\n2.@yahoo.com\n3.@hotmail.com\n4.@outlook.com\n5.@redditmail.com");
			System.out.print("\nPlease enter your selection : ");
			int selection = sc.nextInt();
			sc.nextLine();

			System.out.println(
					"\nPlease enter your email username (the part before '@'). Blank spaces are not allowed  : ");
			String email = sc.next();

			switch (selection) {
			case 1:
				alternateEmailAddress = email + "@gmail.com";
				break;
			case 2:
				alternateEmailAddress = email + "@yahoo.com";
				break;
			case 3:
				alternateEmailAddress = email + "@hotmail.com";
				break;
			case 4:
				alternateEmailAddress = email + "@outlook.com";
				break;
			case 5:
				alternateEmailAddress = email + "@redditmail.com";
				break;
			}

			System.out.println("\nYour alternate email address : " + getAlternateEmailAddress());
			System.out.print(
					"\nPlease select option :\n1.CONFIRM alternate email address.\n2.CHANGE alternate email.\n3.CANCEL"
							+ " setting alternate email address.\n\nEnter your option : ");
			confirmChoice = sc.nextInt();
			if (confirmChoice == 1) {
				System.out.println("\n----------Alternate Email ID CONFIRMED----------");
				System.out.println("\n----------ALL SETUPs COMPLETED----------");
				break;
			} else if (confirmChoice == 2) {
				System.out.println("\n----------Alternate Email ID change requested----------");
			} else if (confirmChoice == 3) {
				alternateEmailAddress = "";
				altEmail = false;
				System.out.println("\n----------Alternate Email Setup CANCELLED----------");
				System.out.println("\n----------ALL PROCESSES COMPLETED----------");
				break;
			}
		} // end of while
	}// end of setAlternateEmailAddress()

}// end of program